### ISSUE TITLE
Final Fantasy X reported as corrupted file/unplayable in latest

### ISSUE THREAD

**Issue by Level99OCR** [kode54/foo_psf#3]
Foo_psf from March of this year works fine, but updating to latest makes any song (afaik) show as unplayable/corrupted. No crashes, just not working at all.

**Comment by kode54** [comment]
It doesn't work on actual hardware, either, but this re-rip does:

https://static.kode54.net/ffx.7z

**Comment by Level99OCR** [comment]
Ah, thanks for that. Closing since not actual pluging issue, just rip issue. Appreciated.

**Comment by TeamFail** [comment]
I noticed that my FFX and Rockman 8 beta rips weren't playing, apparently being corrupted - although the same sets played in Droidsound-E properly. After running @kode54's re-rip of FFX, I noticed that some of the songs in his rip also don't play for some reason, one of them ended up crashing Foobar2000 altogether (Opening 326 - I Can Fly fails to play,and has FB2K completely quit responding), so I'm not sure if it's completely fixed or not yet.
